# Generated by Django 5.1.7 on 2025-03-31 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oc_lettings_site", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="letting",
                    name="address",
                ),
                migrations.DeleteModel(
                    name="Address",
                ),
                migrations.DeleteModel(
                    name="Letting",
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(name="Address", table="lettings_address"),
                migrations.AlterModelTable(name="Letting", table="lettings_letting"),
            ],
        ),
    ]
