# Generated by Django 5.1.7 on 2025-03-31 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "oc_lettings_site",
            "0002_remove_letting_address_delete_address_delete_letting",
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="Profile",
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(name="Profile", table="profiles_profile")
            ],
        ),
    ]
